name: Percy Snapshots

on:
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  nonce:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.nonce.outputs.result }}
    steps:
    - id: nonce
      run: echo "::set-output name=result::${{ github.run_id }}-$(date +%s)"

  call_snapshots_default:
    needs: nonce
    uses: yext/slapshot-reusable-workflows/.github/workflows/percy_snapshots.yml@v1
    with:
      build_script: npm run setup-test-site && npm run build-test-site
      percy_script: npx percy exec --parallel -- node tests/percy/index.js
      PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
      PERCY_PARALLEL_TOTAL: 4
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  call_snapshots_iframe:
    needs: nonce
    uses: yext/slapshot-reusable-workflows/.github/workflows/percy_snapshots.yml@v1
    with:
      build_script: npm run setup-test-site && npm run build-test-site
      percy_script: npx percy exec --parallel -- node tests/percy/index.js iframe
      PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
      PERCY_PARALLEL_TOTAL: 4
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  call_snapshots_spanish:
    needs: nonce
    uses: yext/slapshot-reusable-workflows/.github/workflows/percy_snapshots.yml@v1
    with:
      build_script: npm run setup-test-site && npm run build-test-site
      percy_script: npx percy exec --parallel -- node tests/percy/index.js spanish
      PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
      PERCY_PARALLEL_TOTAL: 4
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  call_snapshots_rtl:
    needs: nonce
    uses: yext/slapshot-reusable-workflows/.github/workflows/percy_snapshots.yml@v1
    with:
      build_script: npm run setup-test-site && npm run build-test-site
      percy_script: npx percy exec --parallel -- node tests/percy/index.js rtl
      PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
      PERCY_PARALLEL_TOTAL: 4
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
