name: WCAG tests

on:
  pull_request:
    branches: [develop, hotfix/*, release/*, support/*]

jobs:
  call_WCAG_test:
    uses:  yext/answers-headless/.github/workflows/wcag_test_reuse.yml@dev/test-reusable-workflows
    with:
      build_script: 'npm run setup-test-site && npm run build-test-site'
      node_version: '16.x'
